name: Ci/cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'X64', 'main' ]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t static-webpage .
    - name: Run docker image
      run: docker run -d -p 8080:80 static-webpage


